import xml.sax.saxutils
from typing import Optional, Dict
from fastapi import APIRouter, Response, HTTPException, status
from pydantic import BaseModel

router = APIRouter(prefix="/voice", tags=["Voice Telephony & Indic TTS"])

# In-memory storage for synthesized audio bytes and speech scripts
AUDIO_CACHE: Dict[str, bytes] = {}
TEXT_CACHE: Dict[str, str] = {}


class SpeechSynthesizeRequest(BaseModel):
    text: str
    speaker: Optional[str] = "priya"
    language_code: Optional[str] = "hi-IN"


@router.get("/audio/{audio_id}")
async def get_audio_file(audio_id: str):
    """
    Serves raw WAV audio generated by Sarvam AI for Twilio <Play> streaming.
    """
    audio_bytes = AUDIO_CACHE.get(audio_id)
    if not audio_bytes:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Audio segment not found or expired",
        )
    return Response(content=audio_bytes, media_type="audio/wav")


@router.get("/twiml")
async def get_twiml_instructions(
    audio_id: Optional[str] = None,
    text_id: Optional[str] = None,
    text: Optional[str] = None,
):
    """
    Returns TwiML XML instructions for Twilio Voice Calls.
    Uses <Play> for studio-quality Sarvam AI Indic voice,
    or <Say voice="Polly.Aditi" language="hi-IN"> for native Indian accent fallback.
    """
    if audio_id and audio_id in AUDIO_CACHE:
        audio_url = f"https://paytm-collections-backend.onrender.com/api/v1/voice/audio/{audio_id}"
        xml_content = f"""<?xml version="1.0" encoding="UTF-8"?>
<Response>
    <Play>{audio_url}</Play>
</Response>"""
        return Response(content=xml_content, media_type="application/xml")

    # Speech script lookup
    raw_text = text or (TEXT_CACHE.get(text_id) if text_id else "नमस्ते, यह पेटीएम कलेक्शंस से आवश्यक स्मरण पत्र है।")
    escaped_text = xml.sax.saxutils.escape(raw_text)

    # Use Amazon Polly Aditi (native Indian Hindi female voice)
    xml_content = f"""<?xml version="1.0" encoding="UTF-8"?>
<Response>
    <Say voice="Polly.Aditi" language="hi-IN">{escaped_text}</Say>
</Response>"""
    return Response(content=xml_content, media_type="application/xml")


@router.post("/synthesize")
async def synthesize_voice_prompt(req: SpeechSynthesizeRequest):
    """
    Synthesizes speech using Sarvam AI Indic engine and registers TwiML URL.
    """
    from backend.app.providers.sarvam_adapter import sarvam_adapter
    result = await sarvam_adapter.synthesize_speech(
        text=req.text,
        language_code=req.language_code,
    )
    return result
