import logging
from typing import Optional, Dict
from datetime import datetime, timezone
from backend.app.schemas.schemas import VerificationStatus

logger = logging.getLogger(__name__)


class MockPaymentGateway:
    """
    MOCKED Payment Gateway for Paytm AI Workforce.
    
    IMPORTANT: This is explicitly a synthetic mock implementing the Free Tier Architecture.
    It returns deterministic states (PAID, NOT_PAID, PENDING, UNKNOWN, ERROR)
    to verify and test the collections agent's decision loop safely.
    """

    # In-memory overrides for simulator and test cases
    _invoice_status_overrides: Dict[str, VerificationStatus] = {}

    @classmethod
    def set_invoice_status(cls, invoice_id: str, status: VerificationStatus):
        """Used by test suites and demo simulator to force specific verification outcome."""
        cls._invoice_status_overrides[invoice_id] = status
        logger.info(f"[MOCKED PAYMENT GATEWAY] Override set for invoice {invoice_id} -> {status.value}")

    @classmethod
    def clear_overrides(cls):
        cls._invoice_status_overrides.clear()

    @classmethod
    async def verify_payment(
        cls,
        invoice_id: str,
        amount: Optional[float] = None,
        currency: str = "INR",
    ) -> Dict[str, any]:
        """
        Simulates payment gateway inquiry with deterministic behavior.
        
        Returns:
            dict containing:
                - status: VerificationStatus (PAID, NOT_PAID, PENDING, UNKNOWN, ERROR)
                - is_mock: True
                - provider: "MOCK_PAYTM_GATEWAY"
                - verified_at: ISO timestamp
                - provider_reference: synthetic transaction ID or None
                - error_code: string error if status == ERROR
        """
        logger.info(f"[MOCKED PAYMENT GATEWAY] Checking payment status for invoice: {invoice_id}")

        # 1. Check if test suite or simulator specified an override
        if invoice_id in cls._invoice_status_overrides:
            status = cls._invoice_status_overrides[invoice_id]
        else:
            # Deterministic default based on invoice ID conventions:
            # - 'paid' in invoice_id -> PAID
            # - 'pending' in invoice_id -> PENDING
            # - 'error' in invoice_id -> ERROR
            # - otherwise NOT_PAID
            inv_lower = invoice_id.lower()
            if "paid" in inv_lower:
                status = VerificationStatus.PAID
            elif "pending" in inv_lower:
                status = VerificationStatus.PENDING
            elif "error" in inv_lower:
                status = VerificationStatus.ERROR
            else:
                status = VerificationStatus.NOT_PAID

        now_str = datetime.now(timezone.utc).isoformat()
        ref_id = f"MOCK_TXN_{abs(hash(invoice_id)) % 100000000:08d}" if status == VerificationStatus.PAID else None

        result = {
            "status": status.value,
            "is_mock": True,
            "provider": "MOCK_PAYTM_GATEWAY",
            "invoice_id": invoice_id,
            "amount": amount,
            "currency": currency,
            "provider_reference": ref_id,
            "verified_at": now_str,
            "error_code": "MOCK_GATEWAY_TIMEOUT" if status == VerificationStatus.ERROR else None,
            "notice": "This verification was generated by [MOCKED PAYMENT GATEWAY] for safety.",
        }

        logger.info(f"[MOCKED PAYMENT GATEWAY] Verification result for {invoice_id}: status={status.value}")
        return result


payment_gateway = MockPaymentGateway()
